name: synergy
channels:
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy        
    - matplotlib
    - deap 
    - ipywidgets 
    - IPython
    - pip:
        - array
        - random
        - json
        - math 
        - ctypes
        - warnings