channels:
    - conda-forge
    - defaults
dependencies:
    - python==3
    - numpy        
    - matplotlib
    - deap 
    - ipywidgets 
    - IPython
    - pip:
        - array
        - random
        - json
        - math 
        - ctypes
        - warnings