name: synergy
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - array    
    - random
    - json
    - matplotlib
    - math 
    - deap 
    - ctypes
    - ipywidgets 
    - warnings
    - IPython