name: synergy
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy        
    - matplotlib
    - deap 
    - ctypes
    - ipywidgets 
    - warnings
    - IPython
    - pip:
        - array
        - random
        - json
        - math 